### ISSUE TITLE
Only show public and your own private purposes

### ISSUE THREAD

**Issue by wmdbMattes** [wmdbsystems/WMDB.BudgetPlan#56] opened 2015-07-07 07:27 UTC
When reimbursing the select box should show purposes based on these two optGroups:

* Open Public Purposes
* Open Private Purposes (Purposes being assigned to yourself)

**Comment by andreasfernandez** [comment] 2015-12-04 19:52
Please check whether this issue is a dupe of #27.

**Closed** 2015-12-04 19:53 UTC
